# Generated by Django 4.1.9 on 2023-06-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0006_tweety_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweety',
            name='tweet',
        ),
    ]
