# Generated by Django 4.1.9 on 2023-06-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0007_remove_tweety_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweety',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweety',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweety',
            name='tweeticerik',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
