# Generated by Django 4.1.9 on 2023-06-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0008_tweety_address_tweety_name_tweety_tweeticerik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweety',
            name='name',
        ),
    ]
