# Generated by Django 4.1.9 on 2023-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0011_remove_tweety_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicted_Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
