# Generated by Django 4.1.9 on 2023-06-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0012_predicted_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicted_tweets',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_tweets',
            name='tweet',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
